[project]
name = "pythonproject"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bcrypt>=5.0.0",
    "dashscope>=1.25.16",
    "langchain>=1.2.15",
    "langchain-community>=0.4.1",
    "langchain-openai>=1.1.12",
    "mysql-connector-python>=9.6.0",
    "pypdf>=6.9.2",
    "streamlit>=1.56.0",
    "streamlit-cookies-manager>=0.2.0",
    "streamlit-js-eval>=1.0.0",
]

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true
